export const ADD_MARKER = "ADD_MARKER";
export const GET_MARKER = "GET_MARKER";
export const GET_MARKERS = "GET_MARKERS";
export const DELETE_MARKER = "DELETE_MARKER";

export const SET_CENTER_POSITION = "SET_CENTER_POSITION";
export const TOGGLE_POLYGON_MODE = "TOOGLE_POLYGON_MODE";
export const SELECT_MARKER_ICON = "SELECT_MARKER_ICON";

export const ADD_POLYGON_POINT = "ADD_POLYGON_POINT";
export const ADD_CURRENT_POLYGON_TO_POLYGONS =
  "ADD_CURRENT_POLYGON_TO_POLYGONS";
export const LOAD_POLYGONS = "LOAD_POLYGONS";
